//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace book_store
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user83_dbEntities : DbContext
    {
        public user83_dbEntities()
            : base("name=user83_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bs_author> bs_author { get; set; }
        public virtual DbSet<bs_edition> bs_edition { get; set; }
        public virtual DbSet<bs_order> bs_order { get; set; }
        public virtual DbSet<bs_order_status> bs_order_status { get; set; }
        public virtual DbSet<bs_publisher> bs_publisher { get; set; }
        public virtual DbSet<bs_release_form> bs_release_form { get; set; }
        public virtual DbSet<bs_role> bs_role { get; set; }
        public virtual DbSet<bs_user> bs_user { get; set; }
        public virtual DbSet<bs_user_edition> bs_user_edition { get; set; }
    }
}
