//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace book_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class bs_user_edition
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public Nullable<int> id_order { get; set; }
        public int id_edition { get; set; }
        public Nullable<int> current_page { get; set; }
        public bool is_on_bookshelf { get; set; }
        public Nullable<int> quantity { get; set; }
        public string review { get; set; }
        public Nullable<int> mark { get; set; }
    
        public virtual bs_edition bs_edition { get; set; }
        public virtual bs_order bs_order { get; set; }
        public virtual bs_user bs_user { get; set; }
    }
}
